spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crypto_wallet
    username: db_user
    password: db_pass
    driverClassName: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always

bitbank:
  public-api-endpoint-url: https://public.bitbank.cc
  endpoint-url: https://api.bitbank.cc
  api-version: v1
  api-key: ${BITBANK_API_KEY}
  api-secret: ${BITBANK_API_SECRET}

bybit:
  endpoint-url: https://api.bybit.com
  api-version: v3
  api-key: ${BYBIT_API_KEY}
  api-secret: ${BYBIT_API_SECRET}

excelapi:
  endpoint-url: https://api.excelapi.org